version: '3.9'

services:
  
  server-mysql:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    ports:
      - "3306:3306"
    hostname: server-mysql
    container_name: server-mysql
    stdin_open: true
    tty: true
    volumes:
      - ./dev/mysql:/var/lib/mysql
    restart: always

  toposervice-mongodb:
    image: mongo:4.4.2-bionic
    ports:
      - "27017:27017"
    hostname: toposervice-mongodb
    container_name: toposervice-mongodb
    stdin_open: true
    tty: true
    volumes:
      - ./dev/mongo:/data/db
    restart: always

  eolo-rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: eolo-rabbitmq
    container_name: eolo-rabbitmq
    stdin_open: true
    tty: true
    volumes:
      - ./dev/rabbitmq:/var/lib/rabbitmq
    restart: always