version: '3.9'

services:
  
  server-mysql:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    ports:
      - "3306:3306"
    hostname: server-mysql
    container_name: server-mysql
    stdin_open: true
    tty: true
    volumes:
      - ./prod/mysql:/var/lib/mysql
    restart: always

  toposervice-mongodb:
    image: mongo:4.4.2-bionic
    environment:
      - MONGO_INITDB_DATABASE=topo
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    hostname: toposervice-mongodb
    container_name: toposervice-mongodb
    stdin_open: true
    tty: true
    volumes:
      - ./prod/mongo:/data/db
    restart: always

  eolo-rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: eolo-rabbitmq
    container_name: eolo-rabbitmq
    stdin_open: true
    tty: true
    volumes:
      - ./prod/rabbitmq:/var/lib/rabbitmq
    restart: always

  toposervice:
    image: drojo/eoloplanner-toposervice:1.0
    environment:
      - SPRING_DATA_MONGODB_HOST=toposervice-mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=topo
      - SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE=admin
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=password
    ports:
      - 8080:8080
    hostname: toposervice
    container_name: toposervice
    depends_on:
      - toposervice-mongodb

  weatherservice:
    image: drojo/eoloplanner-weatherservice:1.0
    environment:
      - GRPC_HOST=weatherservice
      - GRPC_PORT=9090
    ports:
      - 9090:9090

  planner:
    image: drojo/eoloplanner-planner:1.0
    environment:
      - SPRING_RABBITMQ_HOST=eolo-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=root
      - SPRING_RABBITMQ_PASSWORD=password
      - GRPC_HOST=weatherservice
      - GRPC_PORT=9090
      - TOPOSERVICE_HOST=toposervice
      - TOPOSERVICE_PORT=8080
    hostname: planner
    container_name: planner
    depends_on:
      - eolo-rabbitmq
      - toposervice
      - weatherservice
    restart: on-failure

  server:
    image: drojo/eoloplanner-server:1.0
    environment:
      - RABBITMQ_HOST=eolo-rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PROTOCOL=amqp
      - RABBITMQ_USER=root
      - RABBITMQ_PASS=password
      - MYSQL_HOST=server-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=eoloplantsDB
      - MYSQL_USER=root
      - MYSQL_PASS=password
    ports:
      - 3000:3000
    hostname: server
    container_name: server
    depends_on: 
      - server-mysql
      - eolo-rabbitmq
    # -t param defines the timeout in seconds, zero value means no timeout, so it waits until the resource will be available
    command: ["./wait-for-it.sh", "-t", "0", "server-mysql:3306", "--", "./wait-for-it.sh", "-t", "0", "eolo-rabbitmq:5672", "--", "node", "src/server.js"]
    restart: on-failure
